### ISSUE TITLE
Subscriptions import: Question

### ISSUE THREAD

**Issue by kunalsood** [bazqux/bazqux-api#4]
The documentation for the endpoint `https://www.bazqux.com/reader/api/0/import/opml` says: `Post OPML data here. It will return percent of feeds currently processed (integer number in plain text).`

Could you please provide more details about how the endpoint expects the OPML Data to be posted.
Should it be http body? or `multipart/form-data`?
What should the `Content-Type` header be?

I have tried several different combinations, and keep getting `400 Bad Request` error, either without any response message, or with the message: `No opml specified`.

**Comment by vshabanov** [comment]
It should be `application/x-www-form-urlencoded` with OPML file contents in the `opml` parameter.

**Comment by kunalsood** [comment]
Awesome, thanks! :)
