### ISSUE TITLE
Does 'nt=...' not work for all streams?

### ISSUE THREAD

**Issue by kunalsood** [bazqux/bazqux-api#8]
I'm trying to fetch IDs of read items in a user's account that are at most 3 days old.

`https://www.bazqux.com/reader/api/0/stream/items/ids?output=json&s=user/-/state/com.google/read&n=10000&includeAllDirectStreamIds=true&nt=1625395784` is what I tried. But, it seems to include IDs of items that're from August 2017. Am I doing something wrong? Or, is 'nt' not supported for this stream?

**Comment by vshabanov** [comment]
`nt` is a *maximum download* time in seconds. So it won't return items downloaded after this time.

You should use `ot`. But it could still return old posts for freshly added feeds since it's download time, not the published time.

**Comment by kunalsood** [comment]
Understood. Thanks!
